/**
 * By Penny Rowe using starter code from dchiu
 */
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <string.h>
#include <stdio.h>
#include "mmm.h"

int **mat1, **mat2, **mat3;
int matdim;

/**
 * Allocate and initialize the matrices on the heap. Populate
 * the input matrices with random integers from 0 to 99
 */
void mmm_init()
{
	// Intialize random number generator
	time_t t;
	srand((unsigned)time(&t));

	// malloc a size N array of pointers to ints
	mat1 = (int **)malloc(sizeof(int *) * matdim);
	mat2 = (int **)malloc(sizeof(int *) * matdim);
	mat3 = (int **)malloc(sizeof(int *) * matdim);

	// iterate through each row and malloc a size N array of ints
	for (int i = 0; i < matdim; i++)
	{
		mat1[i] = (int *)malloc(sizeof(int) * matdim);
		mat2[i] = (int *)malloc(sizeof(int) * matdim);
		mat3[i] = (int *)malloc(sizeof(int) * matdim);
	}

	// Populate the array with dummy values for now
	// TODO: Use random numbers
	for (int i = 0; i < matdim; i++)
		for (int j = 0; j < matdim; j++)
		{
			mat1[i][j] = rand() % 100;
			mat2[i][j] = rand() % 100;
			mat3[i][j] = rand() % 100;
		}

	return;
}

/**
 * Reset a given matrix to zeroes
 * @param matrix pointer to a 2D array
 */
void mmm_reset(double **matrix)
{
	// TODO
	return;
}

/**
 * Free up memory allocated to all matrices
 */
void mmm_freeup()
{
	// free each row
	for (int i = 0; i < matdim; i++)
	{
		// Free ith rwo
		free(mat1[i]);
		free(mat2[i]);
		free(mat3[i]);
		// remove dangling pointers
		mat1[i] = NULL;
		mat2[i] = NULL;
		mat3[i] = NULL;
	}
	// free original arrays
	free(mat1);
	free(mat2);
	free(mat3);
	// remove dangling pointers
	mat1 = NULL;
	mat2 = NULL;
	mat2 = NULL;
	return;
}

/**
 * Sequential MMM
 */
void mmm_seq()
{
	// TODO - code to perform sequential MMM
	return;
}

/**
 * Parallel MMM
 */
void *mmm_par(void *args)
{
	// TODO - code to perform parallel MMM
	return NULL;
}

/**
 * Verifies the correctness between the matrices generated by
 * the sequential run and the parallel run.
 *
 * @return the largest error between two corresponding elements
 * in the result matrices
 */
double mmm_verify()
{
	// TODO
	return -1;
}

/**
 * Print a matrix
 */
void mmm_print1(int **array)
{
	for (int i = 0; i < matdim; i++)
	{
		for (int j = 0; j < matdim; j++)
		{
			printf("%d ", array[i][j]);
		}
		printf("\n");
	}
}

/**
 * Print the matrices
 */
void mmm_print()
{
	printf("\nmatrix 1:\n");
	mmm_print1(mat1);

	printf("\nmatrix 2:\n");
	mmm_print1(mat2);

	printf("\nmatrix 3:\n");
	mmm_print1(mat3);

	return;
}
